//
//  ExposurePlansListView.swift
//  beatphobia
//
//  Created for Guided Exposure Plans feature
//

import SwiftUI
import RealmSwift

struct ExposurePlansListView: View {
    @Environment(\.colorScheme) var colorScheme
    @EnvironmentObject var authManager: AuthManager
    @ObservedResults(ExposurePlan.self) var allPlans
    @Binding var isTabBarVisible: Bool
    
    @State private var planToDelete: ExposurePlan?
    @State private var showDeleteConfirmation = false
    @State private var showPlanDetail: ExposurePlan?
    @State private var cachedUserPlans: [ExposurePlan] = []
    
    var userPlans: [ExposurePlan] {
        cachedUserPlans
    }
    
    var body: some View {
        ZStack {
            AppConstants.backgroundColor(for: colorScheme)
                .ignoresSafeArea()
            
            if cachedUserPlans.isEmpty && allPlans.isEmpty {
                emptyStateView
            } else if cachedUserPlans.isEmpty {
                // Show loading state while cache is being built
                ProgressView()
            } else {
                listView
            }
        }
        .navigationTitle("My Exposure Plans")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                Menu {
                    Button(action: {
                        createNewPlan()
                    }) {
                        Label("Create Plan", systemImage: "plus.circle")
                    }
                    
                    Button(action: {
                        createAutogeneratedPlan()
                    }) {
                        Label("Auto-Generate Plan", systemImage: "sparkles")
                    }
                } label: {
                    Image(systemName: "plus")
                        .font(.system(size: 18, weight: .semibold))
                        .foregroundColor(AppConstants.primaryColor)
                }
            }
        }
        .sheet(item: $showPlanDetail) { plan in
            NavigationStack {
                PlanDetailView(plan: plan, isTabBarVisible: $isTabBarVisible, shouldAutoGenerate: shouldAutoGenerate)
                    .onDisappear {
                        shouldAutoGenerate = false
                    }
            }
        }
        .alert("Delete Plan?", isPresented: $showDeleteConfirmation) {
            Button("Cancel", role: .cancel) { }
            Button("Delete", role: .destructive) {
                if let plan = planToDelete {
                    Task {
                        await deletePlan(plan)
                    }
                }
            }
        } message: {
            Text("This plan will be permanently deleted from all your devices.")
        }
        .task {
            // Initialize cache asynchronously to avoid blocking
            await MainActor.run {
                cachedUserPlans = allPlans.filter { !$0.isDeleted }.sorted(by: { $0.createdAt > $1.createdAt })
            }
        }
        .onChange(of: allPlans.count) { _, _ in
            // Update cache when plans change (non-blocking)
            Task { @MainActor in
                cachedUserPlans = allPlans.filter { !$0.isDeleted }.sorted(by: { $0.createdAt > $1.createdAt })
            }
        }
    }
    
    // MARK: - Empty State
    
    private var emptyStateView: some View {
        VStack(spacing: 24) {
            Spacer()
            
            // Icon
            Image(systemName: "map.fill")
                .font(.system(size: 64))
                .foregroundColor(AppConstants.primaryColor.opacity(0.6))
            
            // Headline
            Text("Build your path to recovery.")
                .font(.system(size: 24, weight: .bold, design: .serif))
                .foregroundColor(AppConstants.primaryTextColor(for: colorScheme))
                .multilineTextAlignment(.center)
            
            // Body Text
            Text("Exposure plans help you take recovery one step at a time. Create your first plan to get started. You've got this.")
                .font(.system(size: 16))
                .foregroundColor(AppConstants.secondaryTextColor(for: colorScheme))
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)
            
            // Button
            Button(action: {
                createNewPlan()
            }) {
                Text("Create Your First Plan")
                    .font(.system(size: 18, weight: .bold))
                    .foregroundColor(.white)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 16)
                    .background(
                        LinearGradient(
                            colors: [AppConstants.primaryColor, AppConstants.primaryColor.opacity(0.8)],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
                    .cornerRadius(16)
                    .shadow(color: AppConstants.primaryColor.opacity(0.3), radius: 10, y: 5)
            }
            .padding(.horizontal, 40)
            .padding(.top, 8)
            
            Spacer()
        }
    }
    
    // MARK: - List View
    
    private var listView: some View {
        List {
            ForEach(userPlans) { plan in
                NavigationLink(destination: PlanDetailView(plan: plan, isTabBarVisible: $isTabBarVisible, shouldAutoGenerate: false)) {
                    PlanRowView(plan: plan)
                }
                .buttonStyle(PlainButtonStyle())
            }
            .onDelete(perform: deletePlans)
        }
        .listStyle(PlainListStyle())
    }
    
    // MARK: - Helper Methods
    
    private func createNewPlan() {
        Task {
            await createNewPlanAsync()
        }
    }
    
    private func createNewPlanAsync() async {
        let realm = await MainActor.run {
            try? Realm()
        }
        guard let realm = realm else { return }
        
        // Create new plan in Realm
        let newPlan = ExposurePlan()
        newPlan.name = ""
        newPlan.createdAt = Date()
        newPlan.updatedAt = Date()
        newPlan.needsSync = true
        newPlan.isSynced = false
        
        let planToShow = await MainActor.run {
            var result: ExposurePlan?
            try! realm.write {
                realm.add(newPlan)
                // Get the managed version from Realm
                result = realm.object(ofType: ExposurePlan.self, forPrimaryKey: newPlan.id)
            }
            return result
        }
        
        // Now we can observe it (use the managed version from Realm)
        if let plan = planToShow {
            await MainActor.run {
                showPlanDetail = plan
            }
        }
    }
    
    private func createAutogeneratedPlan() {
        Task {
            await createAutogeneratedPlanAsync()
        }
    }
    
    private func createAutogeneratedPlanAsync() async {
        let realm = await MainActor.run {
            try? Realm()
        }
        guard let realm = realm else { return }
        
        // Create new plan in Realm
        let newPlan = ExposurePlan()
        newPlan.name = "Auto-Generated Plan"
        newPlan.createdAt = Date()
        newPlan.updatedAt = Date()
        newPlan.needsSync = true
        newPlan.isSynced = false
        
        let planToShow = await MainActor.run {
            var result: ExposurePlan?
            try! realm.write {
                realm.add(newPlan)
                // Get the managed version from Realm
                result = realm.object(ofType: ExposurePlan.self, forPrimaryKey: newPlan.id)
            }
            return result
        }
        
        // Now we can observe it (use the managed version from Realm)
        if let plan = planToShow {
            await MainActor.run {
                showPlanDetail = plan
                // Set flag to auto-generate when the view appears
                shouldAutoGenerate = true
            }
        }
    }
    
    @State private var shouldAutoGenerate = false
    
    private func deletePlans(at offsets: IndexSet) {
        for index in offsets {
            let plan = userPlans[index]
            planToDelete = plan
            showDeleteConfirmation = true
        }
    }
    
    private func deletePlan(_ plan: ExposurePlan) async {
        let realm = await MainActor.run {
            try? Realm()
        }
        guard let realm = realm else {
            await MainActor.run {
                planToDelete = nil
            }
            return
        }
        
        // Thaw the frozen object before modifying
        let livePlan = await MainActor.run {
            plan.thaw()
        }
        guard let livePlan = livePlan else {
            await MainActor.run {
                planToDelete = nil
            }
            return
        }
        
        // Soft delete the plan
        await MainActor.run {
            try! realm.write {
                livePlan.isDeleted = true
                livePlan.updatedAt = Date()
                livePlan.needsSync = true
                livePlan.isSynced = false
                
                // Also soft delete all targets
                for target in livePlan.targets {
                    target.isDeleted = true
                    target.updatedAt = Date()
                    target.needsSync = true
                    target.isSynced = false
                }
            }
            planToDelete = nil
            // Update cache
            cachedUserPlans = allPlans.filter { !$0.isDeleted }.sorted(by: { $0.createdAt > $1.createdAt })
        }
    }
}

// MARK: - Plan Row View

struct PlanRowView: View {
    @Environment(\.colorScheme) var colorScheme
    let plan: ExposurePlan
    @State private var summary: String = ""
    @AppStorage("setting.miles") private var enableMiles = false
    
    var body: some View {
        HStack(spacing: 16) {
            // Icon
            ZStack {
                Circle()
                    .fill(AppConstants.primaryColor.opacity(0.15))
                    .frame(width: 50, height: 50)
                
                Image(systemName: "map.fill")
                    .font(.system(size: 22))
                    .foregroundColor(AppConstants.primaryColor)
            }
            
            // Content
            VStack(alignment: .leading, spacing: 6) {
                Text(plan.name.isEmpty ? "Untitled Plan" : plan.name)
                    .font(.system(size: 18, weight: .semibold))
                    .foregroundColor(AppConstants.primaryTextColor(for: colorScheme))
                    .lineLimit(1)
                
                Text(summary.isEmpty ? "Loading..." : summary)
                    .font(.system(size: 14))
                    .foregroundColor(AppConstants.secondaryTextColor(for: colorScheme))
            }
            
            Spacer()
        }
        .padding(.vertical, 8)
        .onAppear {
            // Only calculate summary when this row becomes visible
            summary = beatphobia.calculatePlanSummary(plan, useMiles: enableMiles)
        }
    }
}

